### ISSUE TITLE
Js

### ISSUE THREAD

**Issue by buronbekdev** [sardorbek23/first#2]
<img width="626" alt="Screenshot 2023-10-31 at 16 29 34" src="https://github.com/sardorbek23/first/assets/87988979/2c1ad588-a2d7-44a0-93a8-7eb80efbd14b">

js code xato bor yoki ko'p 1 qator code bolardi okaxon

**Comment by sardorbek23** [comment]
yordam bering

**Comment by buronbekdev** [comment]
hop

**Comment by buronbekdev** [comment]
hop
